# kickstart travis.
language: java

# need to override travis 'install' since it will try gpg sign and fail.
install: mvn clean package -DskipTests=true

notifications:
  email:
    recipients:
      - marcus.lacerda@gmail.com
    on_success: change
    on_failure: always
