--liquibase formatted sql

--changeset marcus:2

create table remember_me_token (
	id integer generated by default as identity (start with 1), 
	date timestamp, series varchar(255), 
	token_value varchar(255), 
	username varchar(255), 
primary key (id));

create table user_account (
	id integer generated by default as identity (start with 100),
	account_locked boolean, 
	display_name varchar(255), 
	email varchar(255), 
	image_url varchar(255), 
	password varchar(64), 
	trusted_account boolean,  
	web_site varchar(255), 
primary key (id));
alter table user_account add constraint user_account_email_uk  unique (email);

create table user_social_connection (
	id integer generated by default as identity (start with 1), 
	access_token varchar(255), 
	display_name varchar(255), 
	expire_time bigint, 
	image_url varchar(255), 
	profile_url varchar(255), 
	provider_id varchar(255), 
	provider_user_id varchar(255), 
	rank integer, 
	refresh_token varchar(255), 
	secret varchar(255), 
	user_id varchar(255), 
primary key (id));	